config/routes.rb
Rails.application.routes.draw do

  # mount_push_type

  # get 'welcome/index'

  root 'welcome#index'
  get 'donate', to: 'pages#donate', as: 'donate'
  get 'terms', to: 'pages#terms', as: 'terms'
  get 'privacy_policy', to: 'pages#privacy_policy', as: 'privacy_policy'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/next_market.rb
class NextMarket
  attr_accessor :today, :location, :address, :date, :time

  def initialize
    @today = Date.today
    @location = set_location
    @address = set_address
    @date = set_date
    @time = set_time
  end

  def set_location
    it_is_summer? ? "ByLineBank Parking Lot" : "The Honky Tonk"
  end

  def set_address(today = Time.now)
    it_is_summer? ? "18th and Halsted" : "1800 S Racine"
  end

  def set_date
    it_is_summer? ? next_sunday : next_third_sunday_of_the_month
  end

  def set_time
    it_is_summer? ? "9am - 2pm" : "11am - 3pm"
  end

  def it_is_summer?
    (last_sunday_in_month(5) < today) && (today < last_sunday_in_month(10))
  end

  def last_sunday_in_month(month_number)
    last_day_of_month = Date.new(Date.today.year, month_number, -1)

    last_day_of_month - last_day_of_month.wday
  end

  def next_sunday
    sunday_after(today)
  end

  def sunday_after(day)
    day + (7 - day.wday)
  end

  def third_sunday_of_month(month)
    first_of_the_month = Date.new(today.year, month, 1)
    if first_of_the_month.wday == 0
      first_of_the_month + 14
    else
      sunday_after(first_of_the_month) + 14
    end
  end

  def next_third_sunday_of_the_month
    if today < third_sunday_of_month(today.month)
      third_sunday_of_month(today.month)
    else
      third_sunday_of_month(today.month + 1)
    end
  end

  def map_location
    it_is_summer? ? "Pilsen+Farmers+Market" : "Honky+Tonk"
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  protect_from_forgery with: :exception

  def donate
    @content = {title: "Coming Soon!"}
  end

  def terms
    @content = {title: "Terms and Conditions (\"Terms\")"}
  end

  def privacy_policy
    @content = {title: "Privacy Policy"}
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  protect_from_forgery with: :exception

  def index
    puts File.expand_path(Rails.root)
    puts File.expand_path(Rails.root) + "/app/assets/images/"
    @banner_photos = Dir.entries(
      File.expand_path(
        Rails.root
      ) + "/app/assets/images/intro-banner/"
    ).select {|filename| filename[-3..-1] == "png"}

    @next_market = NextMarket.new
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/application/_favicon.html.erb
<link rel="apple-touch-icon" sizes="180x180" href="<%= asset_path 'favicon/apple-touch-icon.png' %>">
<link rel="icon" type="image/png" href="<%= asset_path 'favicon/favicon-32x32.png' %>" sizes="32x32">
<link rel="icon" type="image/png" href="<%= asset_path 'favicon/favicon-16x16.png' %>" sizes="16x16">
<link rel="manifest" href="<%= asset_path 'favicon/manifest.json' %>">
<link rel="mask-icon" href="<%= asset_path 'favicon/safari-pinned-tab.svg' %>" color="#5bbad5">
<link rel="shortcut icon" href="<%= asset_path 'favicon/favicon.ico' %>">
<meta name="apple-mobile-web-app-title" content="Pilsen Community Market">
<meta name="application-name" content="Pilsen Community Market">
<meta name="msapplication-config" content="<%= asset_path 'favicon/browserconfig.xml' %>">
<meta name="theme-color" content="#ffffff">

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Pilsen Community Market</title>
    <%= csrf_meta_tags %>
    <%= render 'application/favicon' %>

    <meta name="viewport" content="width=device-width, initial-scale=1">

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <!-- Navigation -->
    <nav class="navbar navbar-default navbar-fixed-top topnav" role="navigation">
      <div class="container topnav">
        <!-- Brand and toggle get grouped for better mobile display -->
        <div class="navbar-header">
          <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <%= link_to(image_tag("chicken.png", height: "35"), root_path, class: "navbar-brand topnav") %>
        </div>
        <!-- Collect the nav links, forms, and other content for toggling -->
        <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
          <ul class="nav navbar-nav navbar-right">
            <%= render "partials/nav" %>
          </ul>
        </div>
        <!-- /.navbar-collapse -->
      </div>
    </nav>

    <div class="body-container">
      <%= content_for?(:pages) ? yield(:pages) : yield %>
      </div>
    <!-- Footer -->
    <footer class="footer">
        <div class="container center">
            <div class="row">
                <div class="col-lg-12">
                  <div class="col-sm-8 col-sm-offset-2 text-center">
                    <ul class="list-inline">
                      <%= render "partials/nav" %>
                    </ul>
                    <div class="fine-print small">
                    <ul class="list-inline copyright text-muted">
                      <li>
                        <%= link_to "Terms and Conditions", terms_path %>
                      </li>
                      <li class="menu-divider">&sdot;</li>
                      <li>
                        <%= link_to "Privacy Policy", privacy_policy_path %>
                      </li>
                    </ul>
                    <p class="copyright text-muted small">website design adapted from <%= link_to "startbootstrap.com", "https://startbootstrap.com/template-overviews/landing-page/", target: "_blank" %></p>
                    </div>
                  </div>
                </div>
            </div>
        </div>
    </footer>
  </body>
</html>

app/views/layouts/pages.html.erb
<% content_for :pages do %>
    <div class="row">
      <h1 class="section-heading col-lg-12 text-center"><%= @content[:title] %></h1>
      <div class="col-md-6 col-sm-8 col-sm-offset-2 col-md-offset-3">
        <%= yield %>
      </div>
    </div>
<% end %>
<%= render template: "layouts/application" %>

app/views/pages/donate.html.erb
      <%= image_tag("seedlings.jpg", class: "img-responsive img-rounded") %>

app/views/pages/privacy_policy.html.erb
      <p class="text-center">Your information is collected solely for the purpose of processing your donation. This informtion is kept confidential and is not shared.</p>

app/views/pages/terms.html.erb
<p>Last updated: November 06, 2016</p>
<p>Please read these Terms of Service (&quot;Terms&quot;, &quot;Terms of Service&quot;) carefully before using the http://www.pilsenmarket.org website (the &quot;Service&quot;) operated by Pilsen Community Market (&quot;us&quot;, &quot;we&quot;, or &quot;our&quot;).</p>
<p>Your access to and use of the Service is conditioned on your acceptance of and compliance with these Terms. These Terms apply to all visitors, users and others who access or use the Service.</p>
<p>By accessing or using the Service you agree to be bound by these Terms. If you disagree with any part of the terms then you may not access the Service. This Terms of Service was created with the <a href="https://termsfeed.com/terms-conditions/generator/">Terms and Conditions Generator from TermsFeed</a>.</p>
<p><strong>Links To Other Web Sites</strong></p>
<p>Our Service may contain links to third-party web sites or services that are not owned or controlled by Pilsen Community Market.</p>
<p>Pilsen Community Market has no control over, and assumes no responsibility for, the content, privacy policies, or practices of any third party web sites or services. You further acknowledge and agree that Pilsen Community Market shall not be responsible or liable, directly or indirectly, for any damage or loss caused or alleged to be caused by or in connection with use of or reliance on any such content, goods or services available on or through any such web sites or services.</p>
<p>We strongly advise you to read the terms and conditions and privacy policies of any third-party web sites or services that you visit.</p>
<p><strong>Governing Law</strong></p>
<p>These Terms shall be governed and construed in accordance with the laws of Illinois, United States, without regard to its conflict of law provisions.</p>
<p>Our failure to enforce any right or provision of these Terms will not be considered a waiver of those rights. If any provision of these Terms is held to be invalid or unenforceable by a court, the remaining provisions of these Terms will remain in effect. These Terms constitute the entire agreement between us regarding our Service, and supersede and replace any prior agreements we might have between us regarding the Service.</p>
<p><strong>Changes</strong></p>
<p>We reserve the right, at our sole discretion, to modify or replace these Terms at any time. If a revision is material we will try to provide at least 30 days notice prior to any new terms taking effect. What constitutes a material change will be determined at our sole discretion.</p>
<p>By continuing to access or use our Service after those revisions become effective, you agree to be bound by the revised terms. If you do not agree to the new terms, please stop using the Service.</p>
<p><strong>Contact Us</strong></p>
<p>If you have any questions about these Terms, please contact us.</p>

app/views/partials/_nav.html.erb
<li>
  <%= link_to "About", root_path(anchor: "about") %>
</li>
<li class="menu-divider">&sdot;</li>
<li>
  <%= link_to "Location", root_path(anchor: "location") %>
</li>
<li class="menu-divider">&sdot;</li>
<li>
  <%= link_to "Contact", root_path(anchor: "contact") %>
</li>
<li class="menu-divider">&sdot;</li>
<li>
  <%= link_to "Donate", donate_path %>
</li>

app/views/welcome/index.html.erb
    <!-- Header -->
    <div class="intro-header" style="background: url(../assets/intro-banner/<%= @banner_photos.shuffle.pop %>) no-repeat center center; background-size: cover;">
        <div class="container">

            <div class="row">
                <div class="col-lg-12">
                    <div class="intro-message">
                      <h1><img class="img-responsive logo" src="assets/PCM-Logo2014.png"></h1>
                    </div>
                </div>
            </div>

        </div>
        <!-- /.container -->

    </div>
    <!-- /.intro-header -->

    <!-- Page Content -->
    <!-- /.content-section-a -->
    <a id="about"></a>
    <div class="content-section-a">
      <div class="container">

        <div class="row">
          <!-- <div class="col&#45;lg&#45;5 col&#45;sm&#45;5"> -->
            <div class="clearfix"></div>
            <!-- <div class="col&#45;md&#45;12"> -->
            <h2 class="section-heading col-lg-6 text-center">About Us</h2>
            <!-- </div> -->
          <div class="col-lg-6 col-sm-8 col-md-7 float-right custom-padding-a">
            <div class="col-lg-10 col-lg-offset-1">
              <img class="img-responsive img-rounded" src="assets/dancers.jpg" alt="">
            </div>
          </div>
            <p class="lead">Pilsen Community Market strives to provide fresh, quality farm products, arts and crafts, music and information to a diverse community while embracing and connecting with surrounding neighborhoods.<br><br>Pilsen Community Market is a 501(c)(3) not-for-profit corporation. Contributions are tax deductible as allowed by law.<br><br>Stop by for local and organic produce, meat, eggs, cheese, honey, freshly baked breads and other pastries, tamales, handmade jewelry, and more!</p>
          <!-- </div> -->
        </div>

      </div>
      <!-- /.container -->

    </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    <!-- divider -->


	<a id="location"></a>
    <div class="content-section-b">

        <div class="container">
            <div class="row">
                <div class="col-sm-10 col-sm-offset-1">
                    <div class="clearfix"></div>
                    <div class="row">
                    <h2 class="section-heading sm-text-right col-lg-6 col-lg-offset-1 col-sm-5 col-sm-offset-1">Join Us At The Next Market!</h2>
                    <p class="lead col-lg-3 col-sm-5"><%= @next_market.date.strftime("%A, %B #{@next_market.date.day.ordinalize}") %><br><%= @next_market.time %><br><%= @next_market.location %><br><%= @next_market.address %></p>
                    </div>
                <div id="map" class= "embed-responsive embed-responsive-4by3">
                  <iframe class="embed-responsive-item" src="https://www.google.com/maps/embed/v1/place?key=<%= ENV["GOOGLE_MAPS_API_KEY"] %>&q=<%= @next_market.map_location %>,Chicago+IL" allowfullscreen>
                  </iframe>
                </div>
                </div>
            </div>

        </div>
        <!-- /.container -->

    </div>

    <a id="contact"></a>
    <div class="banner">

      <div class="container">

        <div class="row">
          <div class="col-lg-6">
            <h2>Contact Us:</h2>
          </div>
          <div class="col-lg-6">
            <ul class="list-inline banner-contact-buttons">
              <li>
                <a href="mailto:pilsencommunitymarket@gmail.com" class="btn btn-default btn-lg"><i class="fa fa-envelope-o fa-fw"></i> <span class="network-name">Email</span></a>
              </li>
              <li>
                <a target="_blank" href="https://www.facebook.com/pilsenmarket/" class="btn btn-default btn-lg"><i class="fa fa-facebook-square fa-fw"></i> <span class="network-name">Facebook</span></a>
              </li>
              <li>
                <a target="_blank" href="https://www.instagram.com/pilsencommunitymarket/" class="btn btn-default btn-lg"><i class="fa fa-instagram fa-fw"></i> <span class="network-name">Instagram</span></a>
              </li>
            </ul>
          </div>
        </div>

      </div>
      <!-- /.container -->

    </div>